[workspace]
name = "herdbot"
version = "0.1.0"
description = "A Telegram bot that downloads files/torrents and uploads them to Google Drive"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "==3.14.6"
aria2 = "==1.37.0"
rclone = "==1.74.3"
python-dotenv = "==1.2.2"
ruff = "==0.15.20"
pyright = "==1.1.411"

[pypi-dependencies]
telethon = "==1.44.0"
cryptg = "==0.6.0"

[tasks]
start-bot = "python bot.py"
config-gdrive = "rclone config"
lint = "ruff check"
typecheck = "pyright"
check = { depends-on = ["lint", "typecheck"] }
